overrides:
  esbuild: 0.28.2
  vite: "catalog:"
  vitest: "catalog:"

allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - "@turbo/darwin-64@2.10.10"
  - "@turbo/darwin-arm64@2.10.10"
  - "@turbo/linux-64@2.10.10"
  - "@turbo/linux-arm64@2.10.10"
  - "@turbo/windows-64@2.10.10"
  - "@turbo/windows-arm64@2.10.10"
  - turbo@2.10.10
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vitest: 4.1.10
  vite-plus: 0.2.9
  "@vitest/coverage-v8": 4.1.10
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
